### ISSUE TITLE
where do we find the Framework Repo?

### ISSUE THREAD

**Issue by WizardMan1337** [Heep042/kvm_explorer#1]

**Comment by WizardMan1337** [comment]
im a dunce

**Comment by seeker25** [comment]
You get it going?

**Comment by WizardMan1337** [comment]
Yea

**Comment by seeker25** [comment]
Me too, took a bit of struggling with the library flags + including all these extra files. 
The memory scan part seems to cause an exception. 

But then I just realized you can use GameConqueror instead of this tool, read the VM memory space directly..  I'm still going to keep going with VMREAD though.
